language: python

dist: trusty

python:
  - "3.4"

install:
 - "pip install -r requirements.dev.txt"

script:
 - ./devtools/statuses.py --commit=$(git rev-parse HEAD) --build-id=${TRAVIS_BUILD_ID} --token=${token} --pull-id=${TRAVIS_PULL_REQUEST}
 - ./devtools/coverage.sh


after_success:
 - coveralls
