language: python

cache:
 - pip
 - apt

dist: trusty

python:
  - "3.4"

install:
 - "sudo apt-get install graphviz"
 - "pip install -r requirements.dev.txt"

script:
 - ./devtools/statuses.py --commit=$(git rev-parse HEAD) --build-id=${TRAVIS_BUILD_ID} --token=${token} --pull-id=${TRAVIS_PULL_REQUEST}
 - ./devtools/coverage.sh


after_success:
 - coveralls
