language: python

dist: trusty

python:
  - "3.4"

install:
 - "pip install -r requirements.txt"
 - "pip install pylint"

script:
 - ./scripts/unittests.py
 - ./scripts/coverage.sh
 - ./scripts/lint_check.py
 - ./setup.py check sdist

after_success:
 - coveralls
