language: python

dist: trusty

python:
  - "3.4"

install:
 - "pip install -r requirements.txt"
 - "pip install pylint"

script:
 - ./scripts/statuses.py --commit=$(git rev-parse HEAD) --build-id=${TRAVIS_BUILD}_ID --token=${token}
 - ./scripts/coverage.sh

after_success:
 - coveralls
